tracked_casts:
  - 17540: true # Greater Stoneshield (i 13455) = SPELL_AURA_APPLIED & SPELL_CAST_SUCCESS & SPELL_AURA_REMOVED
  - 17626: true # Flask of the Titans
  - 11405: true # Elixir of the Giants (i 9206) = SPELL_AURA_APPLIED & SPELL_CAST_SUCCESS & SPELL_AURA_REMOVED
  - 17528: true # Mighty Rage Potion
  - 17538: true # Elixir of the Mongoose (i 13452) = SPELL_AURA_APPLIED & SPELL_CAST_SUCCESS & SPELL_AURA_REMOVED
  - 11334: true # Elixir of Greater Agility (i 9187) = SPELL_AURA_APPLIED & SPELL_CAST_SUCCESS & SPELL_AURA_REMOVED
  - 17038: true # Winterfall Firewater (i 12820) = SPELL_AURA_APPLIED & SPELL_CAST_SUCCESS & SPELL_AURA_REMOVED
  - 22756: true # Elemental Sharpening Stone
  - 28891: true # Consecrated Sharpening Stone
  - 17628: true # Flask of Supreme Power
  - 26276: true # Elixir of Greater Firepower (i 21546) = SPELL_AURA_APPLIED & SPELL_CAST_SUCCESS & SPELL_AURA_REMOVED
  - 11474: true # Elixir of Shadow Power (i 9264) = SPELL_AURA_APPLIED & SPELL_CAST_SUCCESS & SPELL_AURA_REMOVED
  - 17539: true # Greater Arcane Elixir (i 13454) = SPELL_AURA_APPLIED & SPELL_CAST_SUCCESS & SPELL_AURA_REMOVED
  - 11390: true # Arcane Elixir (i 9155) = SPELL_AURA_APPLIED & SPELL_CAST_SUCCESS & SPELL_AURA_REMOVED
  - 25122: true # Brilliant Wizard Oil (i 20749) = SPELL_CAST_START & SPELL_CAST_SUCCESS
  - 28898: true # Blessed Wizard Oil
#  - 24363: true # Mageblood potion (i 20007) = DOES NOT WORK
  - 17627: true # Flask of Distilled Wisdom
  - 25123: true # Brilliant Mana Oil (i 20748) = SPELL_CAST_START & SPELL_CAST_SUCCESS
  - 24382: true # Spirit of Zanza (i 20079) = SPELL_AURA_APPLIED & SPELL_CAST_SUCCESS & SPELL_AURA_REMOVED
tracked_buffs:
#  - 18194: true # Nightfin Soup (i 13931) = SPELL_AURA_APPLIED & SPELL_AURA_REFRESH & SPELL_PERIODIC_ENERGIZE & SPELL_AURA_REMOVED
  - 24382: true # Spirit of Zanza (i 20079)
tracked_buffs_by_encounter:
  - 17544: true # Greater Frost Protection Potion (i 13456) = SPELL_AURA_APPLIED & SPELL_CAST_SUCCESS & SPELL_AURA_REMOVED & SPELL_ABSORBED
  - 17548: true # Greater Shadow Protection Potion (i 13459) = SPELL_AURA_APPLIED & SPELL_CAST_SUCCESS & SPELL_AURA_REMOVED & SPELL_ABSORBED
  - 18610: true # Heavy Runecloth Bandage (i 14530) = SPELL_AURA_APPLIED & SPELL_CAST_SUCCESS & SPELL_AURA_REMOVED & SPELL_PERIODIC_HEAL & SPELL_MISSED

tracked_items:
  - 22652: "epic" # Glacial Vest
  - 22654: "epic" # Glacial Gloves
  - 22968: "epic" # Glacial Mantle
  - 22655: "epic" # Glacial Wrists
  - 22658: "epic" # Glacial Cloak
  - 22700: "epic" # Glacial Leggings
  - 23032: "epic" # Glacial Headdress
  - 23020: "epic" # Polar Helmet
  - 22941: "epic" # Polar Shoulder Pads
  - 22661: "epic" # Polar Tunic
  - 22701: "epic" # Polar Leggings
  - 22663: "epic" # Polar Bracers
  - 22662: "epic" # Polar Gloves
  - 23033: "epic" # Icy Scale Coif
  - 22967: "epic" # Icy Scale Spaulders
  - 22664: "epic" # Icy Scale Breastplate
  - 22702: "epic" # Icy Scale Leggings
  - 22665: "epic" # Icy Scale Bracers
  - 22666: "epic" # Icy Scale Gauntlets
  - 23019: "epic" # Icebane Helmet
  - 22940: "epic" # Icebane Pauldrons
  - 22669: "epic" # Icebane Breastplate
  - 22699: "epic" # Icebane Leggings
  - 22671: "epic" # Icebane Bracers
  - 22670: "epic" # Icebane Gauntlets
  - 22707: "epic" # Ramaladni's Icy Grasp
  - 23028: "epic" # Hailstone Band
  - 17904: "epic" # Stormpike Insignia Rank 6
  - 18634: "trinket" # Gyrofreeze Ice Reflector
  - 13534: "rare" # Banshee Finger
  - 14502: "rare" # Frostbite Girdle
  - 13537: "rare" # Chillhide Bracers
  - 17903: "rare" # Stormpike Insignia Rank 5
  - 4327: "rare" # Icy Cloak

world_buffs:
  - 22888: true # Rallying Cry of the Dragonslayer (ONY)
  - 355363: true # Rallying Cry of the Dragonslayer (ONY)
  - 24425: true # Spirit of Zandalar (ZG)
  - 355365: true # Spirit of Zandalar (ZG)
  - 16609: true # Warchief's Blessing (REND)
  - 355366: true # Warchief's Blessing (REND)
  - 22817: true # Fengus' Ferocity (DMT)
  - 22818: true # Mol'dar's Moxie (DMT)
  - 22820: true # Slip'kik's Savvy (DMT)
  - 15366: true # Songflower Serenade (SF)
  - 23768: true # Sayge(s Dark Fortune of Damage (DMF)
  - 23769: true # Sayge's Dark Fortune of Resistance (DMF)

enchants_check: true
enchants_ignored:
  - 15: true # +8 armor (i 2304)
  - 16: true # +16 armor (i 2313)
  - 17: true # +24 armor (i 4265)
  - 18: true # +32 armor (i 8173)
  - 1843: true # +40 armor (i 15564)
enchants_ignored_encounters:
  - 1119: true
