tracked_casts:
#  - 17540: true # Greater Stoneshield (i 13455) = SPELL_AURA_APPLIED & SPELL_CAST_SUCCESS & SPELL_AURA_REMOVED
#  - 11405: true # Elixir of the Giants (i 9206) = SPELL_AURA_APPLIED & SPELL_CAST_SUCCESS & SPELL_AURA_REMOVED
#  - 17538: true # Elixir of the Mongoose (i 13452) = SPELL_AURA_APPLIED & SPELL_CAST_SUCCESS & SPELL_AURA_REMOVED
#  - 11334: true # Elixir of Greater Agility (i 9187) = SPELL_AURA_APPLIED & SPELL_CAST_SUCCESS & SPELL_AURA_REMOVED
#  - 17038: true # Winterfall Firewater (i 12820) = SPELL_AURA_APPLIED & SPELL_CAST_SUCCESS & SPELL_AURA_REMOVED
#  - 26276: true # Elixir of Greater Firepower (i 21546) = SPELL_AURA_APPLIED & SPELL_CAST_SUCCESS & SPELL_AURA_REMOVED
#  - 11474: true # Elixir of Shadow Power (i 9264) = SPELL_AURA_APPLIED & SPELL_CAST_SUCCESS & SPELL_AURA_REMOVED
#  - 17539: true # Greater Arcane Elixir (i 13454) = SPELL_AURA_APPLIED & SPELL_CAST_SUCCESS & SPELL_AURA_REMOVED
#  - 11390: true # Arcane Elixir (i 9155) = SPELL_AURA_APPLIED & SPELL_CAST_SUCCESS & SPELL_AURA_REMOVED
#  - 25122: true # Brilliant Wizard Oil (i 20749) = SPELL_CAST_START & SPELL_CAST_SUCCESS
#  - 24363: true # Mageblood potion (i 20007) = DOES NOT WORK
#  - 25123: true # Brilliant Mana Oil (i 20748) = SPELL_CAST_START & SPELL_CAST_SUCCESS
#  - 17548: true # Greater Shadow Protection Potion (i 13459) = SPELL_AURA_APPLIED & SPELL_CAST_SUCCESS & SPELL_AURA_REMOVED & SPELL_ABSORBED
#  - 18610: true # Heavy Runecloth Bandage (i 14530) = SPELL_AURA_APPLIED & SPELL_CAST_SUCCESS & SPELL_AURA_REMOVED & SPELL_PERIODIC_HEAL & SPELL_MISSED
#  - 17544: true # Greater Frost Protection Potion (i 13456) = SPELL_AURA_APPLIED & SPELL_CAST_SUCCESS & SPELL_AURA_REMOVED & SPELL_ABSORBED
#  - 24382: true # Spirit of Zanza (i 20079) = SPELL_AURA_APPLIED & SPELL_CAST_SUCCESS & SPELL_AURA_REMOVED
tracked_buffs:
#  - 18194: true # Nightfin Soup (i 13931) = SPELL_AURA_APPLIED & SPELL_AURA_REFRESH & SPELL_PERIODIC_ENERGIZE & SPELL_AURA_REMOVED
tracked_items:
